import React from "react";

const CurrencyList = () => {
	return (
		<div>
			{/* <p>Inner Box</p>
			<ul>
				<li>Coin list to go here</li>
			</ul> */}
		</div>
	);
};

export default CurrencyList;

// let testData: ItestData = {
// 	data: [
// 		"Bitcoin",
// 		"Ethereum",
// 		"Tether",
// 		"BNB",
// 		"USD Coin",
// 		"XRP",
// 		"Solana",
// 		"Terra",
// 		"Cardano",
// 		"TerraUSD",
// 		"Binance USD",
// 		"Dogecoin",
// 		"Polkadot",
// 		"Avalanche",
// 		"Shiba Inu",
// 		"Lido Staked Ether",
// 		"Wrapped Bitcoin",
// 		"Dai",
// 		"NEAR Protocol",
// 		"Polygon",
// 		"Cronos",
// 		"TRON",
// 		"Bonded Luna",
// 		"Litecoin",
// 		"Bitcoin Cash",
// 		"Cosmos Hub",
// 		"LEO Token",
// 		"FTX Token",
// 		"Chainlink",
// 		"OKB",
// 		"Algorand",
// 		"Stellar",
// 		"ApeCoin",
// 		"Monero",
// 		"Ethereum Classic",
// 		"Uniswap",
// 		"VeChain",
// 		"Hedera",
// 		"Internet Computer",
// 		"Filecoin",
// 		"Elrond",
// 		"Magic Internet Money",
// 		"cETH",
// 		"Frax",
// 		"The Sandbox",
// 		"Theta Network",
// 		"Axie Infinity",
// 		"Decentraland",
// 		"Tezos",
// 		"DeFiChain",
// 		"PancakeSwap",
// 		"The Graph",
// 		"EOS",
// 		"Fantom",
// 		"STEPN",
// 		"Aave",
// 		"Klaytn",
// 		"THORChain",
// 		"Theta Fuel",
// 		"KuCoin Token",
// 		"Flow",
// 		"BitTorrent",
// 		"cUSDC",
// 		"Zcash",
// 		"Helium",
// 		"IOTA",
// 		"Huobi BTC",
// 		"Chain",
// 		"Frax Share",
// 		"Huobi Token",
// 		"Osmosis",
// 		"eCash",
// 		"Bitcoin SV",
// 		"Convex Finance",
// 		"TrueUSD",
// 		"cDAI",
// 		"Maker",
// 		"Quant",
// 		"NEO",
// 		"Waves",
// 		"Arweave",
// 		"NEXO",
// 		"Kusama",
// 		"Radix",
// 		"BitDAO",
// 		"Celo",
// 		"Synthetix Network Token",
// 		"Gala",
// 		"Enjin Coin",
// 		"Pax Dollar",
// 		"Zilliqa",
// 		"Stacks",
// 		"Harmony",
// 		"Chiliz",
// 		"GateToken",
// 		"Dash",
// 		"Neutrino USD",
// 		"Loopring",
// 		"Celsius Network",
// 		"Lido DAO",
// 	],
// };
